[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.33"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# RPC URLs for different networks
[rpc_endpoints]
sepolia = "https://ethereum-sepolia-rpc.publicnode.com"
polygon = "https://polygon.drpc.org"
localhost = "http://127.0.0.1:8545"
